### ISSUE TITLE
Test and fix message status

### ISSUE THREAD

**Issue by RomaricMourgues** [linagora/Twake#2487]
- [ ] Make sure there is no infinite call

- [ ] Perform an analysis of where the system can break on the number of people

(From Taishia)

- [ ]	In a direct chat with oneself all messages sent recently are marked as unread. The older messages are marked as read though
![Screenshot 2022-09-02 at 09.26.36.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/8c7a9286-8ca2-4f8f-a26d-995be702c4c6)

- [x]	When you press Information, it always states that no one has read the message yet, despite the delivery status 
![Screenshot 2022-09-02 at 09.12.33.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/9c58ffba-4ded-4f68-b4ce-650d4eab5a29)

- [ ]	I believe the message is supposed to be marked as read (two blue checks) when the recipient opens the chat. However, at the moment it is marked as read even if the recipient is simply online 
![Screenshot 2022-09-02 at 09.36.45.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/296df925-1441-4021-9214-e0c16b0c3cae)
![Screenshot 2022-09-02 at 09.36.59.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/0043a5d6-b1fc-47aa-bad0-1a16e4b19c2c)

**Comment by hantt12** [comment]
>  When you press Information, it always states that no one has read the message yet, despite the delivery status
==> This one is fixed

**Comment by hantt12** [comment]
> in a direct chat with oneself all messages sent recently are marked as unread. The older messages are marked as read though

==> This one is fixed

**Comment by hantt12** [comment]
> I believe the message is supposed to be marked as read (two blue checks) when the recipient opens the chat. However, at the moment it is marked as read even if the recipient is simply online

I still find this happen. Posted the issue at https://github.com/linagora/Twake/issues/2516

**Comment by tprudentova** [comment]
The issue with information on who has read the message actually isn't fixed for older messages. When you enter a chat or a channel with only messages older than beginning of September, info always states that no one has read the message. You need to send a new message to the chat, then the issue is fixed. 
![Screenshot 2022-09-20 at 10.15.04.png](https://images.zenhubusercontent.com/61e03d0c21ae7b3b7c6d837c/d2868e4a-75c0-4e07-9df4-84721327aef0)

**Comment by RomaricMourgues** [comment]
Thanks, I created this issue related to your comment: https://github.com/linagora/Twake/issues/2521

**Comment by hantt12** [comment]
> The issue with information on who has read the message actually isn't fixed for older messages. When you enter a chat or a channel with only messages older than beginning of September, info always states that no one has read the message. You need to send a new message to the chat, then the issue is fixed. ![Screenshot 2022-09-20 at 10.15.04.png](https://camo.githubusercontent.com/3e66c5d6a836337f71e4208d569c67ae174ff5ea3b248e0e54409724ba5cd844/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631653033643063323161653762336237633664383337632f64323836386534612d373563302d346530372d396466342d383437323133323761656630)

That one is fixed as I commented above
